/**
 * NotificationEvents - Complete catalog of enterprise notification events in GoBanqo.
 */

const NOTIFICATION_EVENTS = {
    // Authentication
    ACCOUNT_CREATED: 'ACCOUNT_CREATED',
    EMAIL_VERIFIED: 'EMAIL_VERIFIED',
    LOGIN_OTP: 'LOGIN_OTP',
    PASSWORD_RESET: 'PASSWORD_RESET',
    PASSWORD_CHANGED: 'PASSWORD_CHANGED',

    // Tenant
    TENANT_CREATED: 'TENANT_CREATED',
    TENANT_ASSIGNED: 'TENANT_ASSIGNED',
    TENANT_MOVED: 'TENANT_MOVED',
    TENANT_CHECKOUT: 'TENANT_CHECKOUT',
    
    // Rent
    RENT_REMINDER: 'RENT_REMINDER',
    RENT_DUE: 'RENT_DUE',
    RENT_OVERDUE: 'RENT_OVERDUE',

    // Payment
    PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
    PAYMENT_FAILED: 'PAYMENT_FAILED',
    PAYMENT_PENDING: 'PAYMENT_PENDING',

    // Receipt
    RECEIPT_GENERATED: 'RECEIPT_GENERATED',

    // Maintenance
    COMPLAINT_CREATED: 'COMPLAINT_CREATED',
    COMPLAINT_UPDATED: 'COMPLAINT_UPDATED',
    COMPLAINT_RESOLVED: 'COMPLAINT_RESOLVED',

    // Property
    ROOM_ASSIGNED: 'ROOM_ASSIGNED',
    ROOM_CHANGED: 'ROOM_CHANGED',

    // Subscription & System
    PLAN_CHANGED: 'PLAN_CHANGED',
    PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
    INVOICE_GENERATED: 'INVOICE_GENERATED',
    TRIAL_ENDING: 'TRIAL_ENDING',
    SYSTEM_ALERT: 'SYSTEM_ALERT',

    // Backward compatibility aliases
    WELCOME: 'TENANT_CREATED',
    TENANT_REQUEST_ALERT: 'COMPLAINT_CREATED',
    BROADCAST: 'SYSTEM_ALERT'
};

const EVENT_CATEGORIES = {
    AUTH: [
        NOTIFICATION_EVENTS.ACCOUNT_CREATED,
        NOTIFICATION_EVENTS.EMAIL_VERIFIED,
        NOTIFICATION_EVENTS.LOGIN_OTP,
        NOTIFICATION_EVENTS.PASSWORD_RESET,
        NOTIFICATION_EVENTS.PASSWORD_CHANGED
    ],
    TENANT: [
        NOTIFICATION_EVENTS.TENANT_CREATED,
        NOTIFICATION_EVENTS.TENANT_ASSIGNED,
        NOTIFICATION_EVENTS.TENANT_MOVED,
        NOTIFICATION_EVENTS.TENANT_CHECKOUT
    ],
    RENT: [
        NOTIFICATION_EVENTS.RENT_REMINDER,
        NOTIFICATION_EVENTS.RENT_DUE,
        NOTIFICATION_EVENTS.RENT_OVERDUE
    ],
    PAYMENT: [
        NOTIFICATION_EVENTS.PAYMENT_RECEIVED,
        NOTIFICATION_EVENTS.PAYMENT_FAILED,
        NOTIFICATION_EVENTS.PAYMENT_PENDING,
        NOTIFICATION_EVENTS.RECEIPT_GENERATED
    ],
    MAINTENANCE: [
        NOTIFICATION_EVENTS.COMPLAINT_CREATED,
        NOTIFICATION_EVENTS.COMPLAINT_UPDATED,
        NOTIFICATION_EVENTS.COMPLAINT_RESOLVED
    ],
    PROPERTY: [
        NOTIFICATION_EVENTS.ROOM_ASSIGNED,
        NOTIFICATION_EVENTS.ROOM_CHANGED
    ],
    SUBSCRIPTION: [
        NOTIFICATION_EVENTS.PLAN_CHANGED,
        NOTIFICATION_EVENTS.PAYMENT_SUCCESS,
        NOTIFICATION_EVENTS.INVOICE_GENERATED,
        NOTIFICATION_EVENTS.TRIAL_ENDING,
        NOTIFICATION_EVENTS.SYSTEM_ALERT
    ]
};

module.exports = {
    NOTIFICATION_EVENTS,
    EVENT_CATEGORIES
};
